version: "3.8"
services:
  api_server:
    build:
      context: ../../
      dockerfile: ./docker/live/Dockerfile
    env_file:
      - .env.test
    volumes:
      - ../../tsconfig.json:/app/tsconfig.json
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: none

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dev", "-d", "test" ]
      interval: 1s
      timeout: 3s
      retries: 30
    logging:
      driver: none

  tester:
    build:
      context: ../../
      dockerfile: ./docker/test-integration/Dockerfile
    env_file:
      - .env.test
    volumes:
      - ../../test:/app/test
      - ../../src:/app/src
      - ../../dist:/app/dist
      - ../../tsconfig-test-integration.json:/app/tsconfig.json
      - ../../knex-migrations:/app/knex-migrations
      - ../../knexfile.ts:/app/knexfile.ts
    depends_on:
      - api_server
